# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [ ]:
!python -V

Python 3.10.7


# 1.3 Trabalhando com arrays Numpy

In [6]:
import numpy as np


In [7]:
km = np.loadtxt('carros-km.txt') #carrega o arquivo txt em uma array numpy

In [8]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [9]:
anos = np.loadtxt('carros-anos.txt', dtype = int)

In [10]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Obtendo a quilometragem média por ano

In [11]:
km_media = km/ (2022 - anos)

In [12]:
km_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

In [13]:
type(km_media)

numpy.ndarray

Tivemos o nosso primeiro contato com a biblioteca Numpy, do Python. Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python.

O pacote Numpy possui um poderoso objeto array multidimensional, que nos permite realizar um conjunto bastante amplo de operações numéricas, sem a necessidade de utilização de laços for.

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [14]:
2 + 2


4

### Subtração ($-$)

In [15]:
2 - 2

0

### Multiplicação ($*$)

In [16]:
2 * 3

6

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [17]:
10 / 3

3.3333333333333335

In [18]:
10 // 3  #traz somente a parte inteira da divisão

3

### Exponenciação ($**$)

In [19]:
2 ** 3

8

### Resto da divisão ($\%$)

In [20]:
10 % 3

1

In [21]:
10 % 2

0

### Expressões matemáticas

In [22]:
5 * 2 + 3 * 2

16

In [23]:
5 * (2 + 3) * 2

50

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [30]:
5 * 2

10

In [31]:
_

10

In [32]:
_ + 3 * 2

16

In [33]:
_ / 2

8.0

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [39]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0


In [38]:
ano_atual

2022

In [40]:
ano_fabricacao

2003

In [41]:
km_total

44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [43]:
km_media = km_total / (ano_atual - ano_fabricacao)

In [44]:
km_media

2337.3684210526317

In [45]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0

km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2337.3684210526317

In [46]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)

km_total += km_media   #no ano seguinte, mantendo a mesma média, qtos km ele terá rodado.
km_total

46747.36842105263

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [ ]:
ano_atual, ano_fabricacao, km_total = 2022, 2003, 44410.0

In [47]:
ano_atual

2022

In [48]:
ano_fabricacao

2003

In [49]:
km_total

46747.36842105263

In [50]:
ano_atual, ano_fabricacao, km_total = 2022, 2003, 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2337.3684210526317

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [ ]:
ano_atual = 2022

In [52]:
type(ano_atual)

int

In [ ]:
km_total = 44410.0

In [53]:
type(km_total)

float

### Booleanos

In [54]:
zero_km = True

In [55]:
type(zero_km)

bool

In [56]:
zero_km = False

In [57]:
type(zero_km)

bool

### Strings

In [59]:
nome = 'Jetta Variant'
nome

'Jetta Variant'

In [60]:
nome = "Jetta Variant"
nome 

'Jetta Variant'

In [61]:
nome = "Jetta 'Variant'"
nome 

"Jetta 'Variant'"

In [62]:
nome = 'Jetta "Variant"'
nome

'Jetta "Variant"'

In [63]:
carro = '''
  Nome,
  Idade,
  Cor
'''

In [66]:
carro

'\n  Nome,\n  Idade,\n  Cor\n'

In [67]:
type(carro)

str

### None

In [68]:
quilometragem = None

In [69]:
quilometragem

In [70]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [77]:
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [72]:
type(a)

int

In [73]:
type(b)


int

In [74]:
type(c)

str

In [75]:
type(d)

str

In [78]:
a + b

30

In [79]:
c + d

'Python é legal'

In [81]:
# c + a

### Conversões de tipo

Funções int(), float(), str()

In [82]:
str(a)

'10'

In [83]:
type(a)

int

In [85]:
c + str(a)

'Python é 10'

In [86]:
float(a)

10.0

In [87]:
var = 3.141592

In [88]:
type(var)

float

In [89]:
int(var)    # não é arredondamento, ele somente pega a parte inteira do número.

3

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [90]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [ ]:
# Isto é um comentário
ano_atual = 2019
ano_atual

In [ ]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

In [ ]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

In [ ]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [93]:
print('Olá, {}!'.format('Rodrigo'))

Olá, Rodrigo!


In [94]:
print('Olá, {}! Esse é seu acesso de número {}.'.format('Rodrigo', 32))

Olá, Rodrigo! Esse é seu acesso de número 32.


In [95]:
print('Olá, {nome}! Esse é seu acesso de número {acesso}.'.format(nome = 'Rodrigo', acesso = 32))

Olá, Rodrigo! Esse é seu acesso de número 32.


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [96]:
nome = 'Elisangela'
acesso = 302

In [97]:
print(f'Olá, {nome}. Esse é seu acesso de número {acesso}.')

Olá, Elisangela. Esse é seu acesso de número 302.


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [98]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [99]:
type(Acessorios)

list

### Lista com tipos de dados variados

In [101]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [103]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [104]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [105]:
carros = [Carro_1, Carro_2]
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [106]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [107]:
'Rodas de liga' in Acessorios

True

In [108]:
'4 x 4' in Acessorios

False

In [109]:
'Rodas de liga' not in Acessorios


False

In [110]:
'4 x 4' not in Acessorios

True

## *A + B*

Concatena as listas *A* e *B*.

In [111]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [113]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [114]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [115]:
C = A + B

In [116]:
C

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [117]:
len(Acessorios)

8

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [123]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [124]:
Acessorios[0]

'Rodas de liga'

In [125]:
Acessorios[2]

'Piloto automático'

In [126]:
Acessorios[-1]  # Para acessar o último item da lista, usa -1, penúltimo usa -2, e assim sucessivamente

'Sensor de chuva'

In [128]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [129]:
''' Como carros é uma lista de lista, quando passar o primeiro índice, ele pegará a 
informação das listas (as de fora) e quando passar outro índice, ele pegará o que tem dentro dessa lista.
Nesse exemplo, existem duas listas, se passar o índice [0], acessa a primeira lista, se passar o índice [0], 
pegará o primeiro item dessa primeira lista.
'''

carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [131]:
carros[0][0]   #pegou o primeiro item da primeira lista.

'Jetta Variant'

In [132]:
carros[0][-2][1] #o -2 pegou o penúltimo item dessa lista que tb é uma lista. Passei um terceiro índice para acessar um item lá dentro.

'Travas elétricas'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [134]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [135]:
Acessorios[2:6]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento']

In [136]:
Acessorios[2:]   # se não colocar parametro no segundo índice, ele pega até o final da lista

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [137]:
Acessorios[:5]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

**EXERCÍCIO DE LISTAS**

Utilize a lista carros abaixo para responder a questão:

In [138]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]

**Quais os códigos para acessar os itens abaixo:**

1) True

2) 'Teto panorâmico'

3) ['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [139]:
carros[1][3]

True

In [141]:
carros[1][-1][-2]

'Teto panorâmico'

In [143]:
carros[0][-1]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [144]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [146]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemento *x* no final da lista *A*.

In [148]:
Acessorios.append('4 X 4')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4',
 '4 X 4']

In [149]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4',
 '4 X 4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [150]:
Acessorios.pop()

'4 X 4'

In [151]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [152]:
Acessorios.pop(3)

'Rodas de liga'

In [153]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [154]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [155]:
Acessorios.pop()

'4 X 4'

In [156]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [157]:
Acessorios_2 = Acessorios.copy()   # Também funciona Acessorios_2 = Acessorios[:]

In [158]:
Acessorios_2.append('4 x 4')

In [159]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [160]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [161]:
Acessorios_3 = Acessorios_2[:]

In [162]:
Acessorios_3.append('Cambio automatico')

In [163]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [164]:
Acessorios_3

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4',
 'Cambio automatico']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

In [165]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [166]:
for item in Acessorios:
  print(item)

Ar condicionado
Bancos de couro
Piloto automático
Sensor crepuscular
Sensor de chuva
Sensor de estacionamento
Travas elétricas


### Loops com listas

###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [167]:
range(10)

range(0, 10)

In [168]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [174]:
for i in range(10):
  print(f'O quadrado de {i} é = ', i ** 2)

O quadrado de 0 é =  0
O quadrado de 1 é =  1
O quadrado de 2 é =  4
O quadrado de 3 é =  9
O quadrado de 4 é =  16
O quadrado de 5 é =  25
O quadrado de 6 é =  36
O quadrado de 7 é =  49
O quadrado de 8 é =  64
O quadrado de 9 é =  81


In [171]:
quadrado = []

for i in range(10):
  quadrado.append(i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [173]:
#Podemos obter o mesmo resultado com apenas uma linha de código:

[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [1]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [2]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [3]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [5]:
acessorios = []

for lista in dados:
  for item in lista:
    acessorios.append(item)

acessorios


['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [6]:
# Usaremos a função SET para eliminar os valores duplicados da lista

list(set(acessorios))

['Sensor de chuva',
 'Câmbio automático',
 'Ar condicionado',
 'Controle de estabilidade',
 '4 X 4',
 'Travas elétricas',
 'Sensor de estacionamento',
 'Teto panorâmico',
 'Câmera de estacionamento',
 'Rodas de liga',
 'Vidros elétricos',
 'Central multimídia',
 'Painel digital',
 'Freios ABS',
 'Piloto automático',
 'Sensor crepuscular',
 'Bancos de couro']

### List comprehensions

In [7]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [10]:
list(set([item for lista in dados for item in lista]))

['Sensor de chuva',
 'Câmbio automático',
 'Ar condicionado',
 'Controle de estabilidade',
 '4 X 4',
 'Travas elétricas',
 'Sensor de estacionamento',
 'Teto panorâmico',
 'Câmera de estacionamento',
 'Rodas de liga',
 'Vidros elétricos',
 'Central multimídia',
 'Painel digital',
 'Freios ABS',
 'Piloto automático',
 'Sensor crepuscular',
 'Bancos de couro']

# Abaixo um exercício com 3 formas de se obter o mesmo resultado:

In [11]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [12]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [13]:
result = []
for lista in dados:
    for item in lista:
        result.append(item)
result

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [14]:
[item for lista in dados for item in lista]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [16]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2022, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2022, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2022, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2022, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2022, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2022, False],
 ['Carens', 2011, False]]

In [17]:
for lista in dados:
  if (lista[2] == True):
    print(lista)

['DS5', 2022, True]
['A5', 2022, True]


In [18]:
zero_km_Y = []

for lista in dados:
  if (lista[2] == True):
    zero_km_Y.append(lista)

zero_km_Y


[['DS5', 2022, True], ['A5', 2022, True]]

In [19]:
zero_km_N = []

for lista in dados:
  if (lista[2] != True):
    zero_km_N.append(lista)

zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2022, False],
 ['Carens', 2011, False]]

### List comprehensions

In [20]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2022, True], ['A5', 2022, True]]

In [21]:
[lista for lista in dados if lista[2] != True]

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2022, False],
 ['Carens', 2011, False]]

In [24]:
ano = 2003
if (ano == 2003):
    print('OK')

OK


# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [26]:
dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2022, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2022, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2022, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2022, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2022, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2022, False],
 ['Carens', 2011, False]]

In [30]:
zero_km_Y, zero_km_N = [], []

for lista in dados:
  if lista[2] == True:
    zero_km_Y.append(lista)
  else:
    zero_km_N.append(lista)

print(zero_km_Y)
print(zero_km_N)

[['DS5', 2022, True], ['A5', 2022, True]]
[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2022, False], ['Carens', 2011, False]]


#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [ ]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

In [ ]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

In [31]:
a, b, c = [], [], []

In [32]:
for lista in dados:
  if lista[1] <= 2000:
    a.append(lista)
  elif lista[1] > 2000 and lista[1] <= 2010:
    b.append(lista)
  else:
    c.append(lista)

print(f'Carros anteriores a 2000: ', a)
print(f'Carros entre 2000 e 2010: ', b)
print(f'Carros acima de 2010: ', c)

Carros anteriores a 2000:  [['Passat', 1991, False], ['Crossfox', 1990, False]]
Carros entre 2000 e 2010:  [['Jetta Variant', 2003, False], ['Aston Martin DB4', 2006, False], ['Série 3 Cabrio', 2009, False]]
Carros acima de 2010:  [['DS5', 2022, True], ['Palio Weekend', 2012, False], ['A5', 2022, True], ['Dodge Jorney', 2022, False], ['Carens', 2011, False]]


# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [33]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [34]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [35]:
import numpy as np

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [37]:
from numpy import arange

In [38]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [39]:
km = np.array([1000, 2300, 4987, 1500])

In [40]:
km

array([1000, 2300, 4987, 1500])

In [41]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [42]:
km.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [44]:
import numpy as np

In [46]:
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)

In [47]:
km


array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [49]:
km.dtype

dtype('int64')

### Arrays com duas dimensões

In [50]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [51]:
acessorios = np.array(dados)

In [52]:
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [53]:
# Para saber as dimensões das listas, usa lista.shape

km.shape

(258,)

In [55]:
acessorios.shape

(3, 8)

### Comparando desempenho com listas

Porque usar um array numpy se já temos uma lista => pois o desempenho dos arrays numpy é muito melhor.
--



In [56]:
np_array = np.arange(1000000)

In [57]:
py_lista = list(range(1000000))

In [58]:
# %time serve para medir o desempenho em tempo dos nossos códigos

%time for _ in range(100): np_array *= 2

CPU times: user 75.5 ms, sys: 0 ns, total: 75.5 ms
Wall time: 77.9 ms


In [59]:
%time for _ in range(100): py_lista = [x * 2 for x in py_lista]

CPU times: user 9.53 s, sys: 2.49 s, total: 12 s
Wall time: 12 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [5]:
import numpy as np


In [1]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [9]:
# idade = 2022 - anos

In [6]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [7]:
idade = 2022 - anos

In [8]:
idade

array([19, 31, 32,  3, 16])

### Operações entre arrays

In [10]:
km_media = km / idade

In [11]:
km_media

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

### Operações com arrays de duas dimensões

In [12]:
dados = np.array([km, anos])

In [13]:
dados


array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [14]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [15]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [16]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [19]:
km_media = dados[0] / (2022 - dados[1])

In [20]:
km_media

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

In [25]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [26]:
contador = np.arange(10)

In [27]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
item = 6
index = item - 1
contador[index]

5

In [30]:
contador[-1]

9

In [31]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [32]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [33]:
dados[1,2]

1990.0

In [34]:
dados[1][2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [35]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
contador[1:4]

array([1, 2, 3])

In [37]:
contador[1:8:2]

array([1, 3, 5, 7])

In [38]:
# Para pegar os números PARES

contador[::2]

array([0, 2, 4, 6, 8])

In [39]:
# Para pegar os números ÍMPARES

contador[1::2]

array([1, 3, 5, 7, 9])

In [40]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [41]:
# Para calcular a KM Média de alguns veículos específicos:

dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [43]:
dados[:, 1:3]
km_media = dados[:, 1:3][0] / (2022 - dados[:, 1:3][1])
km_media

array([ 184.25806452, 1160.09375   ])

## EXERCÍCIO

Considere o seguinte array:

In [53]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)


Qual o código que permite a seleção, sem utilização de operadores lógicos (and e or), das informações de nome e estado civil, somente das pessoas do sexo masculino.

In [54]:
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [44]:
contador = np.arange(10)
contador 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [46]:
contador[contador > 5]

array([6, 7, 8, 9])

In [47]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [48]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [51]:
maior_2000 = dados[:, dados[1] > 2000]
maior_2000

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [52]:
media_km = maior_2000[0] / (2022 - maior_2000[1])
media_km


array([2337.36842105,    0.        , 1609.8125    ])

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [60]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array. (linhas, colunas)

In [61]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [62]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array. (multiplica linhas por colunas)

In [63]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

(lembrando que em lista poderia ter tipos de dados diferentes, mas no array numpy só permite elementos de um único tipo)

In [64]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [65]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [66]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [67]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [68]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
contador.reshape((5,2))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [71]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [73]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [76]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [77]:
np.array(info_carros).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [79]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [82]:
dados_new.resize((3,5), refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [84]:
dados_new[2] = dados_new[0] / (2022 - dados_new[1])
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2337.36842105,   184.25806452,  1160.09375   ,     0.        ,
         1609.8125    ]])

# 5.5 Estatísticas Descritivas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [86]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [87]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

## *np.column_stack()*

A função é usada para empilhar matrizes 1 dimensão como colunas em uma matriz 2D. Pega uma sequência de matrizes 1D e empilhá-los como colunas para fazer uma única matriz 2D. 

In [88]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [89]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [90]:
np.mean(dataset, axis = 0)  # axis dizer que eixo estou trabalhando, se com as colunas ou as linhas. 0 é coluna

array([ 2007.51162791, 44499.41472868, 98960.51310078])

No caso acima, não faz sentido tirar a média dos anos dos carros, então podemos fazer um slice (fatiamento)

In [92]:
np.mean(dataset[:, 1])

44499.41472868217

In [93]:
np.mean(dataset[:, 2])

98960.51310077519

## EXERCICIOS Média Aritmética

Considerando o array idades, quais são formas corretas de se obter a média aritmética das idades?

In [101]:
idades = np.array([10, 23, 45, 34, 25])

In [102]:
np.sum(idades) / idades.size

27.4

In [103]:
np.mean(idades)

27.4

In [105]:
idades.mean()

27.4

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [94]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [95]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [97]:
dataset[:, 2].sum()

25531812.38

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [98]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [99]:
np.sum(dataset[:, 2])

25531812.38